import {
  ScanText,
  MessageSquare,
  Sparkles,
  Combine,
  Scissors,
  Minimize2,
  Lock,
  Upload,
  Brain,
  FileText,
  Users,
  CheckCircle,
  TrendingUp,
  Zap,
  Shield,
  Download,
  FileOutput,
  FileInput,
  Wand2,
  ImagePlus,
  ImageDown,
  Globe,
  Type,
  Unlock,
  Eye
} from 'lucide-react'

export const proTools = [
  {
    id: 'ai-resume-generator',
    icon: Wand2,
    title: 'AI Resume Generator',
    description: 'Create professional, ATS-optimized resumes with AI',
    solidColor: 'bg-violet-600',
    color: 'from-violet-500 to-purple-700',
    acceptedFiles: '',
    multipleFiles: false,
    minFiles: 0,
    category: 'AI-Powered',
    popularity: 99,
    processingTime: '< 45s',
    features: ['AI-powered generation', 'Multiple templates'],
    isGenerator: true,
    requiresPro: true
  },
  {
    id: 'advanced-ocr',
    icon: ScanText,
    title: 'Advanced OCR Pro',
    description: 'AI-powered text extraction with 99.9% accuracy',
    solidColor: 'bg-cyan-600',
    color: 'from-cyan-500 to-blue-700',
    acceptedFiles: '.pdf,.jpg,.jpeg,.png',
    multipleFiles: false,
    minFiles: 1,
    category: 'AI-Powered',
    popularity: 98,
    processingTime: '< 60s',
    features: ['Multi-language OCR', 'AI enhancement']
  },
  {
    id: 'ai-chat',
    icon: MessageSquare,
    title: 'AI Document Chat',
    description: 'Chat with your PDFs using advanced AI',
    solidColor: 'bg-pink-600',
    color: 'from-pink-500 to-purple-700',
    acceptedFiles: '.pdf,.jpg,.jpeg,.png,.gif,.bmp,.webp,.tiff,.tif',
    multipleFiles: false,
    minFiles: 1,
    category: 'AI-Powered',
    popularity: 95,
    processingTime: '< 30s',
    features: ['GPT-4 powered', 'Context awareness']
  },
  {
    id: 'smart-summary',
    icon: Sparkles,
    title: 'Smart Summary Pro',
    description: 'AI-generated summaries with key insights',
    solidColor: 'bg-amber-500',
    color: 'from-yellow-500 to-orange-700',
    acceptedFiles: '.pdf',
    multipleFiles: false,
    minFiles: 1,
    category: 'AI-Powered',
    popularity: 92,
    processingTime: '< 45s',
    features: ['Key insights', 'Sentiment analysis']
  },
  {
    id: 'pro-merge',
    icon: Combine,
    title: 'Pro Merge',
    description: 'Advanced PDF merging with bookmarks',
    solidColor: 'bg-indigo-600',
    color: 'from-blue-500 to-indigo-700',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 2,
    category: 'Professional',
    popularity: 89,
    processingTime: '< 90s',
    features: ['Auto bookmarks', 'Page numbering']
  },
  {
    id: 'precision-split',
    icon: Scissors,
    title: 'Precision Split',
    description: 'Advanced PDF splitting with custom ranges',
    solidColor: 'bg-emerald-600',
    color: 'from-green-500 to-emerald-700',
    acceptedFiles: '.pdf',
    multipleFiles: false,
    minFiles: 1,
    category: 'Professional',
    popularity: 87,
    processingTime: '< 75s',
    features: ['Custom ranges', 'Batch processing']
  },
  {
    id: 'smart-compress',
    icon: Minimize2,
    title: 'Smart Compress Pro',
    description: 'Intelligent compression with quality control',
    solidColor: 'bg-purple-600',
    color: 'from-purple-500 to-violet-700',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 91,
    processingTime: '< 120s',
    features: ['Quality control', 'Size prediction']
  },
  {
    id: 'password-protect',
    icon: Lock,
    title: 'Password Protect',
    description: 'Military-grade encryption for PDFs',
    solidColor: 'bg-rose-600',
    color: 'from-red-500 to-pink-700',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 1,
    category: 'Security',
    popularity: 85,
    processingTime: '< 60s',
    features: ['AES-256 encryption', 'Permission control']
  },
  {
    id: 'images-to-pdf',
    icon: ImagePlus,
    title: 'Images to PDF Pro',
    description: 'Convert images to PDF with advanced settings',
    solidColor: 'bg-teal-600',
    color: 'from-emerald-500 to-teal-700',
    acceptedFiles: '.jpg,.jpeg,.png,.gif,.bmp,.webp',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 88,
    processingTime: '< 60s',
    features: ['Custom page size', 'Quality control']
  },
  {
    id: 'pdf-to-office',
    icon: FileOutput,
    title: 'PDF to Office',
    description: 'Convert PDF to Word, Excel, PowerPoint',
    solidColor: 'bg-blue-700',
    color: 'from-indigo-500 to-blue-700',
    acceptedFiles: '.pdf',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 96,
    processingTime: '< 90s',
    features: ['Word conversion', 'Excel extraction']
  },
  {
    id: 'office-to-pdf',
    icon: FileInput,
    title: 'Office to PDF',
    description: 'Convert Word, Excel, PowerPoint to PDF',
    solidColor: 'bg-orange-600',
    color: 'from-orange-500 to-red-700',
    acceptedFiles: '.doc,.docx,.xls,.xlsx,.ppt,.pptx,.rtf,.odt,.txt',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 96,
    processingTime: '< 90s',
    features: ['Word to PDF', 'Excel to PDF']
  },
  {
    id: 'advanced-html-to-pdf',
    icon: Globe,
    title: 'Advanced HTML to PDF',
    description: 'Convert webpages to PDF with custom settings',
    solidColor: 'bg-cyan-700',
    color: 'from-teal-500 to-cyan-700',
    acceptedFiles: '.html,.htm',
    multipleFiles: false,
    minFiles: 0,
    category: 'Professional',
    popularity: 82,
    processingTime: '< 60s',
    requiresUrl: true,
    features: ['Full page capture', 'Custom page size']
  },
  {
    id: 'text-to-pdf-pro',
    icon: Type,
    title: 'Text to PDF Pro',
    description: 'Convert text to PDF with custom styles',
    solidColor: 'bg-violet-600',
    color: 'from-violet-500 to-purple-700',
    acceptedFiles: '.txt,.md,.csv',
    multipleFiles: true,
    minFiles: 0,
    category: 'Professional',
    popularity: 84,
    processingTime: '< 45s',
    features: ['Custom fonts', 'Markdown support'],
    requiresTextOrFile: true,
    requiresPro: true
  },
  {
    id: 'image-compress-pro',
    icon: ImageDown,
    title: 'Image Compressor Pro',
    description: 'Advanced image compression with quality control',
    solidColor: 'bg-pink-600',
    color: 'from-pink-500 to-rose-700',
    acceptedFiles: '.jpg,.jpeg,.png,.webp,.gif,.bmp',
    multipleFiles: true,
    minFiles: 1,
    category: 'Professional',
    popularity: 88,
    processingTime: '< 45s',
    features: ['Target file size', 'Quality control'],
    requiresPro: true
  }
]


export const PROCESSING_STEPS_CONFIG = {
  'ai-resume-generator': [
    { name: 'Analyzing Input', icon: Brain },
    { name: 'AI Generation', icon: Wand2 },
    { name: 'Optimizing Content', icon: Sparkles },
    { name: 'Formatting Resume', icon: FileText },
    { name: 'Complete', icon: CheckCircle }
  ],
  'advanced-ocr': [
    { name: 'Uploading File', icon: Upload },
    { name: 'AI Enhancement', icon: Brain },
    { name: 'Text Extraction', icon: ScanText },
    { name: 'Entity Detection', icon: Users },
    { name: 'Complete', icon: CheckCircle }
  ],
  'ai-chat': [
    { name: 'Uploading File', icon: Upload },
    { name: 'Text Processing', icon: FileText },
    { name: 'Creating Embeddings', icon: Brain },
    { name: 'AI Initialization', icon: MessageSquare },
    { name: 'Complete', icon: CheckCircle }
  ],
  'smart-summary': [
    { name: 'Uploading File', icon: Upload },
    { name: 'Text Analysis', icon: Brain },
    { name: 'Generating Summary', icon: Sparkles },
    { name: 'Sentiment Analysis', icon: TrendingUp },
    { name: 'Entity Extraction', icon: Users },
    { name: 'Complete', icon: CheckCircle }
  ],
  'pro-merge': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Processing PDFs', icon: FileText },
    { name: 'Merging Documents', icon: Combine },
    { name: 'Optimizing Output', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'precision-split': [
    { name: 'Uploading File', icon: Upload },
    { name: 'Analyzing Structure', icon: Eye },
    { name: 'Splitting Pages', icon: Scissors },
    { name: 'Creating Archive', icon: Download },
    { name: 'Complete', icon: CheckCircle }
  ],
  'smart-compress': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Analyzing Content', icon: Eye },
    { name: 'Optimizing Images', icon: TrendingUp },
    { name: 'Compressing PDFs', icon: Minimize2 },
    { name: 'Complete', icon: CheckCircle }
  ],
  'password-protect': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Generating Keys', icon: Shield },
    { name: 'Applying Encryption', icon: Lock },
    { name: 'Security Verification', icon: CheckCircle },
    { name: 'Complete', icon: Download }
  ],
  'password-remove': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Verifying Password', icon: Shield },
    { name: 'Removing Protection', icon: Unlock },
    { name: 'Complete', icon: CheckCircle }
  ],
  'images-to-pdf': [
    { name: 'Uploading Images', icon: Upload },
    { name: 'Processing Images', icon: ImagePlus },
    { name: 'Creating PDF', icon: FileText },
    { name: 'Optimizing', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'pdf-to-office': [
    { name: 'Uploading PDF', icon: Upload },
    { name: 'Analyzing Structure', icon: Brain },
    { name: 'Extracting Content', icon: Eye },
    { name: 'Converting Format', icon: FileOutput },
    { name: 'Optimizing Output', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'office-to-pdf': [
    { name: 'Uploading Files', icon: Upload },
    { name: 'Analyzing Content', icon: Brain },
    { name: 'Processing Document', icon: FileText },
    { name: 'Converting to PDF', icon: FileInput },
    { name: 'Optimizing Output', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ],
  'advanced-html-to-pdf': [
    { name: 'Fetching URL', icon: Globe },
    { name: 'Rendering Page', icon: Eye },
    { name: 'Applying Settings', icon: Zap },
    { name: 'Creating PDF', icon: FileText },
    { name: 'Complete', icon: CheckCircle }
  ],
  'text-to-pdf-pro': [
    { name: 'Uploading Text Files', icon: Upload },
    { name: 'Processing Text', icon: Type },
    { name: 'Applying Formatting', icon: Zap },
    { name: 'Creating PDF', icon: FileText },
    { name: 'Complete', icon: CheckCircle }
  ],
  'image-compress-pro': [
    { name: 'Uploading Images', icon: Upload },
    { name: 'Analyzing Images', icon: Eye },
    { name: 'Applying Compression', icon: ImageDown },
    { name: 'Optimizing Output', icon: Zap },
    { name: 'Complete', icon: CheckCircle }
  ]
}
